services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    restart: always
    labels:
      - "dashboard.name=Agenda"
      - "dashboard.url=https://ent.timote.ovh"

  frontend:
    build: ./frontend
    restart: always