name: Deploy Dashboard
on: [push]

jobs:
  deploy:
    runs-on: self-hosted # Ton vieux PC
    steps:
      - uses: actions/checkout@v4

      - name: 🔐 Create .env
        run: |
          echo "MEROSS_IP=${{ secrets.MEROSS_IP }}" > .env
          echo "MEROSS_UUID=${{ secrets.MEROSS_UUID }}" >> .env
          echo "MEROSS_KEY=${{ secrets.MEROSS_KEY }}" >> .env

      - name: 🐳 Docker Build & Run
        run: |
          docker stop dashboard-api || true
          docker rm dashboard-api || true
          docker build -t dashboard-api .
          docker run -d --name dashboard-api -p 8085:8085 --restart always --env-file .env dashboard-api